### ISSUE TITLE
NeurIPS 2021 | Achieving Forgetting Prevention and Knowledge Transfer in Continual Learning

### ISSUE THREAD

**Issue by chufanchen** [chufanchen/read-paper-and-code#118]
https://arxiv.org/abs/2112.02706

**Comment by ChufanSuki** [comment]
### CTR

**CL-plugin** is a full continual learning module designed to interact with a pre-trained model.

Freeze pre-train model to avoid forgetting is not the best choice. 

CTR inserts CL-plugin in two locations of BERT, i.e. in each transformer layer of BERT.

In learning, only the two CL-plugins and the classification heads are trained.

### CL-plugin
