### ISSUE TITLE
Continual Reinforcement Learning with Decision Transformer

### ISSUE THREAD

**Issue by chufanchen** [chufanchen/read-paper-and-code#156]
| Task | L2M | LoRA |
|--------|--------|--------|
| hammer-v2 | Cell | Cell |
| push-wall-v2 | Cell | Cell |
| faucet-close-v2 | Cell | Cell |
| push-back-v2 | Cell | Cell |
| stick-pull-v2 | Cell | Cell | 
| handle-press-side-v2 | Cell | Cell | 
| push-v2 | Cell | Cell | 
| shelf-place-v2 | Cell | Cell | 
| window-close-v2 | Cell | Cell | 
| peg-unplug-side-v2 | Cell | Cell |

**Comment by ChufanSuki** [comment]
Try Slow Learner #158

**Comment by ChufanSuki** [comment]
PCA and t-SNE

**Comment by ChufanSuki** [comment]
LoRA init

**Comment by ChufanSuki** [comment]
Rehearsal

- replay buffer
- generative model(gaussian, kmeans, diffusion)
