### ISSUE TITLE
Random Thoughts

### ISSUE THREAD

**Issue by chufanchen** [chufanchen/read-paper-and-code#168]
Cycle Consistency + Decision Transformer

Like world model, we learn a forward and back dynamic model. Then we use these DMs to constraint decision transformer training using cycle consistency constraints.

**Comment by ChufanSuki** [comment]
I'm curious about performance between World Model(MLP-based and transformer-base) and decision transformer.

**Comment by ChufanSuki** [comment]
crl: offline continual learning + online rehearsal
