### ISSUE TITLE
ICML 2023 | Parameter-Level Soft-Masking for Continual Learning

### ISSUE THREAD

**Issue by chufanchen** [chufanchen/read-paper-and-code#75]
https://arxiv.org/abs/2306.14775

https://github.com/UIC-Liu-Lab/SPG

**Comment by ChufanSuki** [comment]
### Introduction

#### CF

Parameter isolation: learn to mask a sub-network for each task in a shared network. E.g. HAT, SupSup

**Comment by ChufanSuki** [comment]
### Soft-masking of Parameter-level Gradient flow

the importance of a parameter to a task is computed based on its gradient
