### ISSUE TITLE
ICLR 2024 | Class Incremental Learning via Likelihood Ratio Based Task Prediction

### ISSUE THREAD

**Issue by chufanchen** [chufanchen/read-paper-and-code#85]
https://arxiv.org/abs/2309.15048

https://github.com/linhaowei1/TPL

**Comment by ChufanSuki** [comment]
An emerging theoretically justified approach to solving CIL is to combine a TIL technique with an out-of-distribution (OOD) detection method, called the TIL+OOD approach([Kim et al., 2022][1]).

It decomposes the CIL probability of a test sample $x$ of the $j$-th class $y_j^{(t)}$ in task $t$ into two probabilities

$$
\mathbf{P}\left(y_j^{(t)} \mid \boldsymbol{x}\right)=\mathbf{P}\left(y_j^{(t)} \mid \boldsymbol{x}, t\right) \mathbf{P}(t \mid \boldsymbol{x})
$$


[1]: https://arxiv.org/abs/2211.02633 (A theoretical study on solving continual learning)
